### ISSUE TITLE
Milestone 2 Feedback (Pilot studies)

### ISSUE THREAD

**Issue by bxie** [info370/project-es3#2]
Great start!
Some ways to further focus your thinking:
- who are the stakeholders who want to inform? Focusing on informing consumers vs city officials (for example) changes your study.
- what do you want to optimize?

Lastly, be careful with what you are starting. X causes Y is often never that neat and clean in reality. So be mindful of confounding factoring when you're thinking about things like for example "Will lowering the cost of parking _encourage_ people to drive more and thereby negatively impact the environment?"

(no further action is required for this "issue" and you can close it after you've reviewed it)

**Comment by greglnelson** [comment]
Your uncertainties for the info decision context were among the best, if not the best, in the class. 
1. The rate of employment for UW Informatics students is low
2. Inability to find employment post undergrad is a problem for UW Informatics students (maybe they all want to go to grad school)
3. iSchool staff aren’t already doing data driven event organization
4. iSchool students struggle with preparing for all job search methods
5. Are there any job search methods we’re missing?

Your pilot study addressed #4 directly, while the other ones were not addressed. Looking at the csv data from your survey, #1 & #2  don't seem to be true - nearly all have a job & the one person that took over 6 months said they decided to go traveling after graduation (maybe from job search difficulty, unclear, I'm guessing no data to suggest that). While this is from your self-selected sample, which may not be representative but is representative of easy sources of data for you to gather.


For the parking question, you richly analyze the decision context as a system of different actors. I am skeptical that the issue with parking is pricing, since occupancy is already so high. When a city has so many more people and an area, like downtown, is already built up, it seems it may be a pure "not enough space" issue - you should look for analysis of the problem from other organizations (maybe some in the seattle city reports?).
